// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBIxIbcxpouItL8tVCSmxKUZs9GB1I-TIA',
    appId: '1:100619211857:web:365d4ee074a17202ce1470',
    messagingSenderId: '100619211857',
    projectId: 'bachat-aae51',
    authDomain: 'bachat-aae51.firebaseapp.com',
    databaseURL: 'https://bachat-aae51.firebaseio.com',
    storageBucket: 'bachat-aae51.firebasestorage.app',
    measurementId: 'G-VMWZ8FLJGM',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDkXSqwXHqp17m1cf3Zt0L2tDR6-GoYsq0',
    appId: '1:100619211857:ios:87e109234ae9f9f1ce1470',
    messagingSenderId: '100619211857',
    projectId: 'bachat-aae51',
    databaseURL: 'https://bachat-aae51.firebaseio.com',
    storageBucket: 'bachat-aae51.firebasestorage.app',
    androidClientId: '100619211857-fi7tvhk4jars6a4unmh3fb5uvtgctc8m.apps.googleusercontent.com',
    iosClientId: '100619211857-g8vcknng3iu9amnocv1f1ehpkb0m9942.apps.googleusercontent.com',
    iosBundleId: 'com.example.chattyX',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDkXSqwXHqp17m1cf3Zt0L2tDR6-GoYsq0',
    appId: '1:100619211857:ios:ebe347ebe5511b37ce1470',
    messagingSenderId: '100619211857',
    projectId: 'bachat-aae51',
    databaseURL: 'https://bachat-aae51.firebaseio.com',
    storageBucket: 'bachat-aae51.firebasestorage.app',
    androidClientId: '100619211857-fi7tvhk4jars6a4unmh3fb5uvtgctc8m.apps.googleusercontent.com',
    iosClientId: '100619211857-lnhaome3ehhlr6abcar4blc6482p36o1.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatty',
  );
}
